### ISSUE TITLE
delayed_options - custom template

### ISSUE THREAD

**Issue by gEndelf** [vedmack/feedback_me#33]
First of all - thx for this plugin - great job!

It would be nice to have custom template for delayed_options.

**Comment by vedmack** [comment]
Thanks,

You mean that you would like to provide some sort of string with html content?

**Comment by gEndelf** [comment]
@vedmack 
yes, I would like to set custom template

**Comment by vedmack** [comment]
Took me a while... but its done (grab the [0.5.8.beta.1](https://github.com/vedmack/feedback_me/blob/master/beta/jquery.feedback_me.js)), read docs https://github.com/vedmack/feedback_me/blob/master/beta/jquery.feedback_me.js#L211
I have added custom_html_success and custom_html_fail into the delayed_options

Here an example usage (a dirty one)

```
delayed_options: {
	custom_html_success: '<div style="background:green;width:200px;height:200px">Yeees</div>',
	custom_html_fail: '<div style="background:red;width:200px;height:200px">Nooooo</div>',
	send_fail : "Sending failed :(.",
	send_success : "Sent successfully :) , wow! even this message is customizable!!!"
},
```

And in your css

```
.feedback-delayed-custom-dlg {
	position: fixed;
	top:300px;
	left:300px;
	backgroubd:red;
}
```
