### ISSUE TITLE
ajax.beforeSend overriding

### ISSUE THREAD

**Issue by gEndelf** [vedmack/feedback_me#34]
With overriding ajax.beforeSend in plugin - global handler in $.ajaxSetup.beforeSend will be not executed.

**Comment by vedmack** [comment]
Can you show an example of such behavior? because its should be like that, I'm setting beforeSend in my local ajax usage and not touching the global ajaxSetup, and b.t.w quoted from http://api.jquery.com/jquery.ajaxsetup/ 

>Description: Set default values for future Ajax requests. Its use is not recommended.

**Comment by gEndelf** [comment]
python/django requires **csrftoken** in POST params and to avoid each time add param I'm using such code:

```
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if(!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
            xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'));
        }
    }
});
```

**Comment by vedmack** [comment]
fixed, you can try it yourself https://github.com/vedmack/feedback_me/blob/master/beta/jquery.feedback_me.js
