### ISSUE TITLE
do tags into clickable tags filters for datatable - yadcf

### ISSUE THREAD

**Issue by elixir1349** [vedmack/feedback_me#35]
I post here my question http://stackoverflow.com/questions/29005929/do-tags-into-clickable-tags-filters-for-jquery-table-yadcf

I refer to this example:

http://yadcf-showcase.appspot.com/DOM_source_select2.html

I would like add for every tag in column 4 a clickable filtering feature so I can display rows that contains tag1 or tag2 only.

Just another thing
I see that the number of values remains 8 for the Country column and does not change if the number of rows contains perhaps only 2 states. Is possible to fix this because I have a several number of countries or cities?

Thanks

**Comment by vedmack** [comment]
Wrong address...

please open this issue on [yadcf repo](https://github.com/vedmack/yadcf/issues)
