### ISSUE TITLE
Does it has support to add more fields other than the predefined fields

### ISSUE THREAD

**Issue by loganathan-s** [vedmack/feedback_me#37]
I wanted to add more fields to the feedback form other than the predefined fields. For example right now plugin has  fields for email, name and message.

If I want to add new field text area field say "Description" to the feedback form,what needs to be done?does the plugin has the support or do I need to add fields via custom html option only?

**Comment by vedmack** [comment]
You can use the [iframe_url](https://github.com/vedmack/feedback_me/blob/master/js/jquery.feedback_me.js#L176) option, see live sample on [showcase page](http://feedback-me.appspot.com/example_external_iframe.html) , you can inspect that [iframe file](http://feedback-me.appspot.com/external_content.html) that I use on the showcae to get a hold of how it .

Also pay attention that by default the `custom_html` / 'iframe file' will be appended to the current form unless you use the `show_form : false`
