### ISSUE TITLE
Plugin doesn't close when clicking outside

### ISSUE THREAD

**Issue by hajjat** [vedmack/feedback_me#40]
Thanks a lot of the great plugin!
Small issue, plugin doesn't close when I click outside of it although the setting is set to true. There is a small bug:
	function applyCloseOnClickOutside() {
		var jqVersion = $().jquery.split(".");
		jqVersion[0] = +jqVersion[0];
		jqVersion[1] = +jqVersion[1];
	    if (jqVersion[0] >= 1 && jqVersion[1] >= 7) {
              .....
The if statement failed for my jQuery version 2.4.

I fixed it like this:
if (jqVersion[0] > 1 || jqVersion[0] == 1 && jqVersion[1] >= 7) {

**Comment by vedmack** [comment]
Fixed in [0.5.9.beta.1](https://github.com/vedmack/feedback_me/blob/8dda745e091b47825b0c36aea23e22c108cf63e1/js/jquery.feedback_me.js)
