### ISSUE TITLE
Feature Request: a cancel button

### ISSUE THREAD

**Issue by davidklebanoff** [vedmack/feedback_me#42]
It would be nice to have the option to have a cancel button that sits next to the send button. When clicked, the cancel button will clear the forms and will close the feedback dialog.

**Comment by vedmack** [comment]
Adding second button will *steal the focus* from the main and the important "submit" button, and in addition that cancel button will be used by very little portion of users.
Also I haven't seen feedback forms with cancel button at all , [for example look at the following link](https://www.jotform.com/form-templates/category/feedback).
